### ISSUE TITLE
Handling of HTTP error 529 could be improved

### ISSUE THREAD

**Issue by paulchen** [philfry/check_sslscan#4]
The SSL Labs API will return HTTP error 529 in case the servers are overloaded: https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#error-response-status-codes

I think the handling of that situation in the `check_sslscan` could be improved:

```
$ ./check_sslscan.py -H rueckgr.at -w A -c A-
UNKNOWN:
$ echo $?
3
$ curl https://api.ssllabs.com/api/v2/analyze?host=rueckgr.at
{"errors":[{"message":"Running at full capacity. Please try again later."}]} 
```

I dug a bit into the code. What I found out:
 - There is some code in place for handling HTTP 529: https://github.com/philfry/check_sslscan/blob/master/check_sslscan.py#L65-L67
 - Furthermore, a response JSON containing the key `error` is also handled: https://github.com/philfry/check_sslscan/blob/master/check_sslscan.py#L70-L73
 - `urllib.urlrequest.urlopen` raises an instance of `URLError` for protocol errors: https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen
 - There is a separate `expect` block for instances of `URLError`: https://github.com/philfry/check_sslscan/blob/master/check_sslscan.py#L62-L63
 - Therefore, neither the code handling HTTP 529 nor the code handling `error` responses are reached.
 - All of this together leads to the output shown above. From that output, one cannot tell what's actually going on without conducting deeper investigations.

All things considered, I think there is some room for improvement for handling HTTP 529.

I would have submitted a pull request since I guess this is only a small change. However, I'm unsure about the best approach. Maybe simply move the `if` [statement](https://github.com/philfry/check_sslscan/blob/master/check_sslscan.py#L65-L67) from line 65 into the preceding `except` block?

**Comment by philfry** [comment]
Hi @paulchen, thanks for your report!

You're right, the exception handling is faulty. I believe the easiest would be to just delete lines 63 and 64 (`raise Exception(e.reason)` and `except Exception as e:`), but I'll want to test that first.

**Comment by philfry** [comment]
Hi,

should be fixed now.

**Comment by paulchen** [comment]
> should be fixed now.

Thank you very much!
